### PR TITLE
Added Dark/Light mode feature

### PR DESCRIPTION
**Pull request by imsp18**
### Changes Made?

- Added a toggle button which switches between dark and light mode and switches the background image of the website with matching color fonts

### Screenshot

In Dark Mode:
image

In Light Mode: 
image

Working of Button: 
Untitled video - Made with Clipchamp

### CODE REVIEW

**Review by piyushkdas0611 — CHANGES_REQUESTED** [review]
add the button on home page too

**Comment by imsp18** [comment]
Okay, can i raise another issue for the homepage section.

The UI of homepage doesn't match with form page, i would like to make some changes to the homepage too

**Comment by piyushkdas0611** [comment]
Sure i have no problem, but I must warn you that I don't think Hacktober Fest will accept to PRs on the same repo it can be considered spamming. Well if you are doing for Open Source Faith then its okay.

**Comment by imsp18** [comment]
> Sure i have no problem, but I must warn you that I don't think Hacktober Fest will accept to PRs on the same repo it can be considered spamming. Well if you are doing for Open Source Faith then its okay.

I just wanted to contribute, it's okay even if some one else also takes on from here. 

I'll add button to the homepage, will make the navbar component common between the two pages.

**Review by piyushkdas0611 — APPROVED** [review]
Well that's perfect!

**Pull request merged**
