### PR TITLE
Homepage and navbar 

### PR DESCRIPTION
**Pull request by awsmdeep**

### CODE REVIEW

**Comment by awsmdeep** [comment]
hi @piyushkdas0611 added the navbar please have a look

**Comment by piyushkdas0611** [comment]
> hi @piyushkdas0611 added the navbar please have a look

Instead of "form" as navigation link, create "contribute" and link the contribute a tag with the link of the github repo, and move the items of navbar to the right and Profile Card Generator as heading written on the left side of  nav bar. And also try to sync the repo, the repo had some recent changes, since your last commit.

**Comment by awsmdeep** [comment]
@piyushkdas0611 made all the changes that were mentioned , please have a look

**Comment by piyushkdas0611** [comment]
Thanks for contributing do star the repo

**Pull request merged**
